title: ""
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## セッション引き継ぎ
        AI セッション間の引き継ぎ情報を記録します。

  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 今回のセッションで達成したこと
      placeholder: |
        - Issue #XX を完了
        - 機能 YY を実装
    validations:
      required: true

  - type: textarea
    id: related-items
    attributes:
      label: 関連アイテム
      description: 関連する Issue/Discussion とそのステータス
      placeholder: |
        - Issue #19: execSync → spawnSync → Done
        - Issue #20: zod-schema 修正 → Done

  - type: textarea
    id: decisions
    attributes:
      label: 重要な決定
      description: 重要な決定事項
      placeholder: |
        1. Table JSON フォーマットを採用
        2. Discussions を知識管理に活用

  - type: textarea
    id: blockers
    attributes:
      label: ブロッカー
      description: 現在のブロッカー（なければ "None"）
      value: None

  - type: textarea
    id: next-steps
    attributes:
      label: 次のステップ
      description: 次のセッションで取り組むべきこと
      placeholder: |
        - [ ] Issue #XX に着手
        - [ ] YY の調査

  - type: textarea
    id: commits
    attributes:
      label: コミット
      description: 今回のコミット一覧
      placeholder: |
        - `abc1234` feat: add feature X
        - `def5678` fix: resolve issue Y
