title: ""
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## エージェント / 手動レポート
        レビュー結果、実装レポート、デザインレポートを記録します。

  - type: dropdown
    id: report-type
    attributes:
      label: レポートタイプ
      description: レポートの種類
      options:
        - Code Review
        - Security Review
        - Implementation
        - Design
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 実施内容と全体結果の要約
      placeholder: |
        Server Action ファイル5件をレビュー。セキュリティ状態は良好。
        TDDアプローチでユーザープロフィール編集を実装。
    validations:
      required: true

  - type: textarea
    id: findings
    attributes:
      label: 詳細 / 発見事項
      description: 詳細な発見事項、問題点、決定事項、または実装詳細
      placeholder: |
        | 問題 | 場所 | 重大度 | 説明 |
        |------|------|--------|------|
        | 認証チェック欠落 | file.ts:45 | Critical | セッション検証なし |

  - type: textarea
    id: files-involved
    attributes:
      label: 関連ファイル
      description: 作成、変更、またはレビューしたファイル
      placeholder: |
        | ファイル | 目的 / 変更内容 |
        |---------|----------------|
        | `lib/actions/profile.ts` | 新規 Server Action |
        | `components/profile-form.tsx` | フォームコンポーネント変更 |

  - type: checkboxes
    id: verification
    attributes:
      label: 検証
      description: 検証チェックリスト
      options:
        - label: 全テスト合格
        - label: lint エラーなし
        - label: 型チェック合格
        - label: ビルド成功
        - label: 手動検証済み

  - type: textarea
    id: notes
    attributes:
      label: 備考 / 推奨事項
      description: フォローアップタスク、推奨事項、追加コンテキスト
      placeholder: |
        1. **即時対応**: 認証の重大な問題を修正
        2. **マージ前**: レート制限を追加
        3. **将来**: キャッシュ戦略の検討
